version: 2.1

jobs:
  test:
    docker:
      - image: josejc01/contenedor-test-alpine:latest
    steps:
      - checkout
      - run: cd backend && chmod +x mvnw && mvnw test
workflows:
  test_project:
    jobs:
      - test