version: 2.1

jobs:
  test:
    docker:
      - image: josejc01/contenedor-test-alpine:latest
    steps:
      - checkout
      - run: chmod +x mvnw
      - cmd: ./mvnw test
workflows:
  test_project:
    jobs:
      - test